version: 2.1
jobs:
  build_and_deploy_frontend:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install frontend dependencies
          command: |
            cd frontend
            npm install
      - run:
          name: Build frontend
          command: |
            cd frontend
            npm run build
      - run:
          name: Deploy frontend
          command: |
            aws ec2 cp frontend/build/ ec2-instance-ip:/var/www/html

  build_and_deploy_backend:
    docker:
      - image: node:14
    steps:
      - checkout
      - run:
          name: Install backend dependencies
          command: |
            cd backend
            npm install
      - run:
          name: Deploy backend
          command: |
            cd backend
            ./deploy.sh
