version: 2.1
jobs:
  build_frontend:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install frontend dependencies
          command: |
            cd frontend
            npm install
      - run:
          name: Build frontend
          command: |
            cd frontend
            npm run build

  deploy_frontend:
    docker:
      - image: amazon/aws-cli:2.11.20
    steps:
      - checkout
      - run:
          name: Deploy frontend
          command: |
            aws ec2 cp frontend/build/ ec2-instance-ip:/var/www/html

  build_backend:
    docker:
      - image: node:14
    steps:
      - checkout
      - run:
          name: Install backend dependencies
          command: |
            cd backend
            npm install

  deploy_backend:
    docker:
      - image: amazon/aws-cli:2.11.20
    steps:
      - checkout
      - run:
          name: Deploy backend
          command: |
            cd backend
            ./deploy.sh

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_frontend
      - deploy_frontend
      - build_backend
      - deploy_backend
